### ISSUE TITLE
removing "semantria-sdk" from PyPI breaks builds

### ISSUE THREAD

**Issue by GooseYArd** [Semantria/semantria-sdk#11]
We noticed one of our builds that depended on semantria-sdk 3.0.70 began failing this morning. After hunting around we found the commits here to rename the package. We're ok with adjusting the name of the dependency but it also appears that the older releases with the new name are missing from PyPI. Any chance you could preserve the old package and versions? We're also happy to begin using one of the newer releases but need a chance to test it for a while first.

**Comment by george-kozlov** [comment]
Hello,

There are no changes in the code itself so you can easy migrate your application to the new package.
We changed the name because of limitations on PyPl side. Their service doesn’t allow publishing of packages with the same name but for different Python versions.
Because of that we’ve been forced to change the name of the package, but the code remains the same.

Please let me know if you have other concerns.

Regards,
GEORGE KOZLOV
CTO/Co-Founder
Semantria, LLC
T 877.570.1840
E george@semantria.com<mailto:george@semantria.com>
www.semantria.com<http://www.semantria.com/>
This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and contact the sender.
