### ISSUE TITLE
Where is the C++ or Objective-C SDK?

### ISSUE THREAD

**Issue by YingshanDeng** [Semantria/semantria-sdk#9]
I want to use Semantria in iOS app, so Where is the C++ or Objective-C SDK?

**Comment by george-kozlov** [comment]
Hello,

Thanks for reaching out.
We had C++ version of add-in but don't support it anymore as we didn't receive any request for C++ SDK during last year. If you interested in C++ SDK, you can download it from our website using this direct link. The code offered as is because we don't support it for a long time. Anyway, it will simplify your integration process as it implements most of the existing methods, authentication, etc.

https://www.semantria.com/download/SDK/SemantriaCppSDK.tar.gz

Please let me know if you have other questions.

--
Regards,
George

**Comment by YingshanDeng** [comment]
Hi,George

The Semantria Cpp SDK is very useful for me! Thank you!

-- 
YingshanDeng
Sent with Airmail

On 2015年4月7日 at 下午8:12:59, George (notifications@github.com) wrote:

Hello,

Thanks for reaching out.
We had C++ version of add-in but don't support it anymore as we didn't receive any request for C++ SDK during last year. If you interested in C++ SDK, you can download it from our website using this direct link. The code offered as is because we don't support it for a long time. Anyway, it will simplify your integration process as it implements most of the existing methods, authentication, etc.

https://www.semantria.com/download/SDK/SemantriaCppSDK.tar.gz

Please let me know if you have other questions.

Regards,
George

**Comment by YingshanDeng** [comment]
Hi, George

I found a mistake in your website, in this page: https://semantria.com/support/developer/references/processing/

Queue: submit a document or batch of documents for Detailed analysis or submit a collection for Discovery analysis. 

Queue with a GET method and the server will return with an HTTP status.
For example, queuing documents for analysis is like lining up bottles to be filled by the milkman.

It should be POST method. 

-- 
YingshanDeng
Sent with Airmail

On 2015年4月8日 at 下午2:13:52, YingshanDeng (yingshandeng@gmail.com) wrote:

Hi,George

The Semantria Cpp SDK is very useful for me! Thank you!

-- 
YingshanDeng
Sent with Airmail

On 2015年4月7日 at 下午8:12:59, George (notifications@github.com) wrote:

Hello,

Thanks for reaching out.
We had C++ version of add-in but don't support it anymore as we didn't receive any request for C++ SDK during last year. If you interested in C++ SDK, you can download it from our website using this direct link. The code offered as is because we don't support it for a long time. Anyway, it will simplify your integration process as it implements most of the existing methods, authentication, etc.

https://www.semantria.com/download/SDK/SemantriaCppSDK.tar.gz

Please let me know if you have other questions.

Regards,
George

**Comment by george-kozlov** [comment]
Yinghan, thanks for feedback.

Andrea, please address this issue on website.

Regards,
GEORGE KOZLOV
CTO/Co-Founder
Semantria, LLC
T 877.570.1840
E george@semantria.com<mailto:george@semantria.com>
www.semantria.com<http://www.semantria.com/>
This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and contact the sender.

**Comment by YingshanDeng** [comment]
Hi, George

If I analyse text use mismatched language config id, what  will happen? In my test, sometime return FAILED status, sometime return the unexpected data…

Thank you!

-- 
YingshanDeng
Sent with Airmail

On 2015年4月9日 at 下午9:23:55, George (notifications@github.com) wrote:

Closed #9.

**Comment by george-kozlov** [comment]
Hi Yingshan,

Nothing critical will happen. Semantria will analyze text and depending of a content it may return it ass PROCESSED or FAILED.
Because of different settings on different languages, mismatched documents can pass analysis but sentiment won’t be appropriate.
You should detect language by your own and then chose proper configuration.

Semantria offers language detection feature but it doesn’t chose proper configuration automatically.
You can create dedicated configuration just for language detection and then pass documents for analysis.
If you will do that, disable all other limits (options) in that dedicated configuration to speedup analysis.

Regards,
GEORGE KOZLOV
CTO/Co-Founder
Semantria, LLC
T 877.570.1840
E george@semantria.com<mailto:george@semantria.com>
www.semantria.com<http://www.semantria.com/>
This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and contact the sender.
